Implementing an evcs validation.
ie3-institute/PowerSystemDataModel pull request #1003
Opened 2024-02-02 12:38 UTC by staudtMarius

Resolves #879 
Resolves #1000

2024-02-04 20:59 UTC, sebastian-peter requested changes
Looks all good from my side, just some minor syntactic points here

2024-02-04 20:59 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/utils/validation/SystemParticipantValidationUtils.java
> +            evcsInput.getType().getsRated().getValue().doubleValue() < 0d,
You could use `detectNegativeQuantities` here

2024-02-05 10:09 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/utils/validation/SystemParticipantValidationUtils.java
> +   * - its number of charging points is < 1 - its rated power factor is between 0 and 1 - its rated
Should I also change these javadoc lines in other methods?

2024-02-05 10:15 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/utils/validation/SystemParticipantValidationUtils.java
> +   * - its number of charging points is < 1 - its rated power factor is between 0 and 1 - its rated
Sure, why not

2024-02-06 09:02 UTC, sebastian-peter approved these changes
@staudtMarius I fixed some minor errors (if you're curious, [check here](https://github.com/ie3-institute/PowerSystemDataModel/pull/1003/files/8f703f11e4b90e34b22975cac1823b8e595af8bb..4ff74fea4c69f0a66f43df0dace3c408ee2b8f4e)) and now it looks good to go!

2024-02-06 09:03 UTC, merged