Improvements to finding corner points in `IdCoordinateSource`.
ie3-institute/PowerSystemDataModel pull request #1017
Opened 2024-02-21 10:30 UTC by staudtMarius

Resolves #1016

2024-02-23 07:13 UTC, sebastian-peter reviewed
Hmm. To be honest, I don't get the point. You're separating the functionality into two methods - ok, fine. But this is not more efficient, actually. 

Now we're calculating `distances.stream().filter(c -> !corners.contains(c))` on top of what we've been doing before. This had been part of the `List<CoordinateDistance> other` before.

2024-02-23 09:50 UTC, staudtMarius commented
My idea with this PR is to have the part of finding the corners to be accessible from outside.
But I see your point. I changed it with the next commit.

2024-03-01 09:33 UTC, sebastian-peter requested changes
Just one request from my side for now, will look deeper into it later at some point

2024-04-30 12:21 UTC, danielfeismann reviewed
LGTM, just one question to the docs...

2024-04-30 14:28 UTC, staudtMarius commented on docs/readthedocs/models/input/additionaldata/idcoordinatesource.md
> +   :header-rows: 0
It is zero in all the other docs too. Also I just tested changing this and I couldn't see any difference. So I think this should be fine.

2024-05-01 07:46 UTC, danielfeismann commented on docs/readthedocs/models/input/additionaldata/idcoordinatesource.md
> +   :header-rows: 0
Trust me ;) the tables look nicer then. Would be great if you can fix this at the other tables as well.

2024-05-01 15:19 UTC, staudtMarius commented on docs/readthedocs/models/input/additionaldata/idcoordinatesource.md
> +   :header-rows: 0
Ok. I will adapt these parts.

2024-05-01 17:58 UTC, danielfeismann approved these changes
Looks all good to me, thanks for your work done here!

2024-05-01 17:58 UTC, merged