Enable persisting emUnits
ie3-institute/PowerSystemDataModel pull request #1026
Opened 2024-02-29 17:36 UTC by jo-bao

Resolves #1025

2024-02-29 17:43 UTC, jo-bao commented
!test

2024-03-04 09:24 UTC, t-ober commented
!test

2024-03-04 09:38 UTC, t-ober commented
!test

2024-03-04 14:05 UTC, sebastian-peter requested changes

2024-03-04 14:05 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/extractor/HasEm.java
> + * Interface that should be implemented by all elements holding one or more {@link
"one or more" is not correct here

2024-03-04 14:56 UTC, jo-bao commented on src/main/java/edu/ie3/datamodel/models/input/EmInput.java
>          + ", parentEm="
Yes!

2024-03-04 15:32 UTC, sebastian-peter requested changes

2024-03-04 15:32 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/models/input/EmInput.java
>          + ", parentEm="
Don't forget to adapt `toString` here as well 😎

2024-03-04 16:49 UTC, merged