Improving the usage of streams on SQL fetches.
ie3-institute/PowerSystemDataModel pull request #1062
Opened 2024-04-09 10:10 UTC by staudtMarius

Resolves #827

2024-04-24 17:53 UTC, danielfeismann submitted a review, later dismissed
LGTM, but maybe Sebastian would like to have a look as well?

2024-06-13 12:06 UTC, sebastian-peter requested changes

2024-06-13 12:06 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/source/sql/SqlDataSource.java
> +      ps.closeOnCompletion();
1. I think it'd make more sense to call this before the stream is created
2. Checking the JavaDoc of this method, I think this only works if the ResultSet is closed (which then causes the Statement to be closed).

2024-06-13 12:06 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/connectors/SqlConnector.java
> +  public Iterator<Map<String, String>> getSqlIterator(ResultSet rs) {
Looking at the StackOverflow answer that I linked in the issue, isn't the purpose of this iterator to close the resources once we've iterated through the results?

2024-10-25 12:43 UTC, sebastian-peter requested changes

2024-10-25 12:43 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/connectors/SqlConnector.java
> +          return false;
I thnk we should also close the ResultSet on error

2024-10-25 12:43 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/connectors/SqlConnector.java
> +        return extractFieldMap(rs);
Also here. Maybe `extractFieldMap` should not catch the SQLException, but we handle it inside the `next()` method.

2024-11-08 11:19 UTC, sebastian-peter requested changes
Looks good for now and it seems to work. One more request from my side

2024-11-08 18:06 UTC, sebastian-peter approved these changes
Did some last tinkering

2024-11-08 18:06 UTC, merged