Remove parameter storage minimum level from cylindrical thermal storage
ie3-institute/PowerSystemDataModel pull request #1124
Opened 2024-07-23 12:06 UTC by danielfeismann

resolves #1123

2024-08-13 13:12 UTC, sebastian-peter requested changes
Looks good, only have one tiny remark

2024-08-13 13:12 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/io/factory/input/CylindricalStorageInputFactoryTest.groovy
Could also be removed from line 35

2024-08-13 15:03 UTC, danielfeismann commented on src/test/groovy/edu/ie3/datamodel/io/factory/input/CylindricalStorageInputFactoryTest.groovy
Good catch :)

2024-08-14 07:18 UTC, sebastian-peter approved these changes
LGTM

2024-08-14 07:18 UTC, merged