PSDM changes for tap water heat demand
ie3-institute/PowerSystemDataModel pull request #1132
Opened 2024-08-08 15:05 UTC by danielfeismann

resolves #1131

2025-02-20 08:23 UTC, staudtMarius requested changes
Overall, it looks good. I just have some questions.
I think, we should remove the issue #679, since you didn't add charge and discharge power to this PR.

Additional question: @danielfeismann does it make sense, to split this PR into smaller PRs?

2025-02-20 08:23 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/io/source/csv/CsvThermalGridSource.java
>              SourceException.class);
Both collections will contain all storages (cylindrical and hot water). I think you need to call the specific methods.

2025-02-20 08:23 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/io/source/ThermalSource.java
> +        .collect(Collectors.toMap(ThermalStorageInput::getUuid, storage -> storage));
Why did you change the collector?

2025-02-20 08:23 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/io/source/ThermalSource.java
> +        .collect(Collectors.toMap(ThermalStorageInput::getUuid, storage -> storage));
Same as above.

2025-02-20 08:23 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/models/input/container/ThermalGrid.java
> +        + ", #heatStorages="
Why do we add a `#` here?

2025-02-20 08:23 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/models/input/thermal/CylindricalStorageInput.java
> +    ComparableQuantity<Power> pThermalMax;
Why did you make this `package private`?

2025-02-20 08:23 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/models/input/thermal/DomesticHotWaterStorageInput.java
> +    }
I think you can remove these methods, since they copy the behavior of the superior class.

2025-02-20 08:23 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/models/result/thermal/DomesticHotWaterStorageResult.java
> +public class DomesticHotWaterStorageResult extends AbstractThermalStorageResult {
The input model extends the `CylindricalStorageInput`. Why does the result not extend the `CylindricalStorageResult`?

2025-02-20 08:23 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/utils/validation/ThermalValidationUtils.java
> +    if (thermalStorageInput.getClass() == CylindricalStorageInput.class) {
Why did you change this? Couldn't you just switch the order of the inputs to check?

2025-02-20 15:42 UTC, danielfeismann commented on docs/readthedocs/models/input/thermal/domestichotwaterstorage.md
> +Model of a domestic hot water storage using a fluent to store thermal energy.
Good catch!

2025-02-20 16:08 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/models/input/container/ThermalGrid.java
> +        + ", #heatStorages="
Because its the number of houses, storages ... the # indicates number of...

2025-02-20 16:09 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/models/input/thermal/CylindricalStorageInput.java
> +    ComparableQuantity<Power> pThermalMax;
It's not, it was private.

2025-02-20 16:12 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/models/input/thermal/DomesticHotWaterStorageInput.java
> +    }
Oh yes, thanks!

2025-02-20 16:15 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/models/result/thermal/DomesticHotWaterStorageResult.java
> +public class DomesticHotWaterStorageResult extends AbstractThermalStorageResult {
Liked the split into an abstract class more. Will do so for factory, input and results, so its aligned.

2025-02-20 21:10 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/io/source/ThermalSource.java
> +        .collect(Collectors.toMap(ThermalStorageInput::getUuid, storage -> storage));
I mean, why don't you use `collect(toMap())`?

2025-02-20 21:12 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/models/input/thermal/CylindricalStorageInput.java
> +    ComparableQuantity<Power> pThermalMax;
Yes, it was private, but now it is package private.

2025-02-21 07:50 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/io/source/ThermalSource.java
> +        .collect(Collectors.toMap(ThermalStorageInput::getUuid, storage -> storage));
Good question, will adapt it.

2025-02-21 07:59 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/models/input/thermal/CylindricalStorageInput.java
> +    ComparableQuantity<Power> pThermalMax;
To use it at `DomesticHotWaterStorageInputCopyBuilder`. But it could stay private if we make the `CylindricalStorageInputCopyBuilder` protected, right?

2025-02-21 08:36 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/models/input/thermal/CylindricalStorageInput.java
> +    ComparableQuantity<Power> pThermalMax;
Since you removed most of the code in the `DomesticHotWaterStorageInputCopyBuilder`, these fields can even stay private.

2025-02-21 09:22 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/models/input/thermal/CylindricalStorageInput.java
> +    ComparableQuantity<Power> pThermalMax;
I guess this is now obsolete with the change to `AbstractThermalStorageInput`.

2025-02-24 14:26 UTC, staudtMarius requested changes
Found some parts, that can be improved.

2025-02-24 14:26 UTC, staudtMarius commented on docs/uml/main/input/ThermalDatamodelConcept.puml
> +                        DomesticHotWaterStorageInput --|> ThermalStorageInput
You could remove this indent.

2025-02-24 14:26 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/io/factory/input/CylindricalStorageInputFactory.java
> +    final ThermalBusInput bus = data.getBusInput();
This could be moved to the base class.

2025-02-24 14:26 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/io/factory/input/DomesticHotWaterStorageInputFactory.java
> +    final ThermalBusInput bus = data.getBusInput();
Same as in the other test.

2025-02-24 14:26 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/models/input/thermal/DomesticHotWaterStorageInput.java
> +  }
This won't work.

2025-02-24 14:26 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/models/input/thermal/CylindricalStorageInput.java
> +    CylindricalStorageInputCopyBuilder(CylindricalStorageInput entity) {
This should be protected.

2025-02-24 14:26 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/utils/Try.java
> +    T get() throws E, SourceException;
Why is this necessary. We would only expect an exception of type `E` here.

2025-02-25 09:20 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/utils/Try.java
> +    T get() throws E, SourceException;
Good catch. Seems to be an artefact which I didn't removed.

2025-02-25 09:21 UTC, danielfeismann commented on src/test/resources/edu/ie3/datamodel/io/source/csv/_participants/cylindrical_storage_input.csv
> +8851813b-3a7d-4fee-874b-4df9d724e4b3,1.0,test_cylindricalThermalStorage,110.0,,,f15105c4-a2de-4ab8-a621-4bc98e372d92,80.0,1.039154027,20.0,0d95d7f2-49fb-4d49-8636-383a5220384e,977157f4-25e5-4c72-bf34
I thought so first as well. But we have this notation in all tests. Will do in a separate PR.

2025-02-25 09:24 UTC, danielfeismann commented on src/test/resources/edu/ie3/datamodel/io/source/csv/_participants/cylindrical_storage_input.csv
> +8851813b-3a7d-4fee-874b-4df9d724e4b3,1.0,test_cylindricalThermalStorage,110.0,,,f15105c4-a2de-4ab8-a621-4bc98e372d92,80.0,1.039154027,20.0,0d95d7f2-49fb-4d49-8636-383a5220384e,977157f4-25e5-4c72-bf34
moved to #1258

2025-02-25 13:39 UTC, staudtMarius approved these changes
LGTM

2025-02-25 13:45 UTC, merged