Handling no received data from WeatherSource
ie3-institute/PowerSystemDataModel pull request #1145
Opened 2024-08-27 21:11 UTC by PhilippSchmelter

Resolves #554 
Added an explicit Exception for handling no received data from WeatherSource to prevent the pipeline moving on without data.

2024-09-11 14:54 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/exceptions/NoWeatherDataException.java
`NoDataException` and year 2024

2024-09-30 21:24 UTC, PhilippSchmelter commented
Handling CSV-Source done
+ all getWeather() which returned optional
//TODO
REST of
SQL
Influx
Couchbase

2024-11-05 11:27 UTC, danielfeismann reviewed
Thanks for tackling this issue. Just some questions from my side. 

Note to self: Still need to check tests.

2024-11-05 11:27 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/io/source/sql/SqlWeatherSource.java
> +      return null;
Please check for the SonarQube hints for returning an empty map

2024-11-05 16:29 UTC, PhilippSchmelter commented
I still need to write some tests I guess. Checked SonarQube for coverage. There are uncovered Conditions
@sebastian-peter @danielfeismann

2025-07-23 09:49 UTC, danielfeismann commented
@PhilippSchmelter are you plan to add some tests here?

2025-08-10 08:15 UTC, danielfeismann requested changes
Thanks for tackling this. Some points from my side

2025-08-10 08:15 UTC, danielfeismann commented on CHANGELOG.md
> +
Please remove this empty line here

2025-08-10 08:15 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/exceptions/NoDataException.java
> +}
Can't we use some existing exception type here? NullPointerException may not hundred percent correct but matches it almost, right?

2025-08-10 08:15 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/io/source/couchbase/CouchbaseWeatherSource.java
> +        throw new NoDataException("No data found");
It would be great to provide the error message within the exception here.

2025-08-10 08:15 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/io/source/couchbase/CouchbaseWeatherSource.java
> +      throw new NoDataException("No coordinate ID found for the given point.");
same here, providing the information which id  or coordinate failed helps a lot

2025-08-10 08:15 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/io/source/couchbase/CouchbaseWeatherSource.java
> +      throw new NoDataException("Failed to decode weather data.");
Should we add the DecondingFailureException message here again?

2025-08-10 08:15 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/io/source/influxdb/InfluxDbWeatherSource.java
> +        throw new NoDataException("No coordinate ID found for the given point.");
May we give the point here as well?

2025-08-10 08:15 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/io/source/influxdb/InfluxDbWeatherSource.java
> +                      "No weather data available for the given date and coordinate."));
same here

2025-08-10 08:15 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/io/source/influxdb/InfluxDbWeatherSource.java
> +        throw new NoDataException("No coordinate ID found for the given point.");
if so, please check also for sql and cs weather source

2025-08-20 16:42 UTC, PhilippSchmelter commented on src/main/java/edu/ie3/datamodel/exceptions/NoDataException.java
> +}
Technically we defineteley could use the NullPointerException but I would leave it as it is for semantic clarity. This Exception explicitly communicates the specific problem domain. I think I already talked about this with sebastian, not sure tho.

2025-08-20 16:44 UTC, PhilippSchmelter commented on src/main/java/edu/ie3/datamodel/io/source/couchbase/CouchbaseWeatherSource.java
> +        throw new NoDataException("No data found");
I've made some changes. Let me know if this is somewhat you imagined.

2025-08-20 21:15 UTC, PhilippSchmelter commented
> Thanks for tackling this. Some points from my side

I hope I was able to fix the right things or what you meant! Let me know if its good like that.

2025-08-20 22:24 UTC, PhilippSchmelter commented
@danielfeismann 
I think now this Issue should be covered :D
Feel free to check the changes and let me know if something doesnt fit!

2025-08-21 12:13 UTC, danielfeismann requested changes
Thank you for including my points. I do have another one or two points which are a bit unclear to me

2025-08-21 12:13 UTC, danielfeismann commented on CHANGELOG.md
> +- Added explicit handling for cases where no weather data is received from any source [#554](https://github.com/ie3-institute/PowerSystemDataModel/issues/554)
Please move this to the end of this subsection

2025-08-21 12:13 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/exceptions/NoDataException.java
> + * @since 04.09.24
Please remove this, we started this somewhen but not really use this and do not update it when changing parts of methods.

2025-08-21 12:13 UTC, danielfeismann commented on src/test/groovy/edu/ie3/datamodel/io/source/influxdb/InfluxDbWeatherSourceIconIT.groovy
> +    then: "only valid coordinate data is returned"
Do we want this? I think if we would throw an exception when requesting some invalid coordinate, then it should still be thrown if it comes along with valid ones.

2025-08-21 12:13 UTC, danielfeismann commented on src/test/groovy/edu/ie3/datamodel/io/source/influxdb/InfluxDbWeatherSourceCosmoIT.groovy
> +    when: "requesting weather for mixed valid and invalid coordinates"
see this case above

2025-08-21 12:13 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/io/source/influxdb/InfluxDbWeatherSource.java
> +          if (!timeBasedValues.isEmpty()) {
Should it also lead to an exception in case timeBasedValues is empty, since one could assume we would expect weather data when asking for it and those aren't there? Not sure about this, I might have to rethink on this.

2025-08-21 12:13 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/io/source/influxdb/InfluxDbWeatherSource.java
> +          if (!timeBasedValues.isEmpty()) {
Also, testing this would also be great.

2025-08-21 12:13 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/exceptions/NoDataException.java
> +}
Thanks for pointing that out again, I also reendevoured above that this was in one of my previous comments :)

2025-08-21 12:13 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/io/source/couchbase/CouchbaseWeatherSource.java
> +        throw new NoDataException("No data found");
Thanks for including this!

2025-08-21 16:17 UTC, PhilippSchmelter commented on src/main/java/edu/ie3/datamodel/exceptions/NoDataException.java
> + * @since 04.09.24
Alright!

2025-08-21 16:21 UTC, PhilippSchmelter commented on src/test/groovy/edu/ie3/datamodel/io/source/influxdb/InfluxDbWeatherSourceIconIT.groovy
> +    then: "only valid coordinate data is returned"
I dont know if Im wrong at this point, but if I remember and understood correctly the approaches for handling this were not consistent through the various WeatherSources. Still have to check that, yesterday was kind of a long coding session :D
But I will change everything to strict failure if no or damaged data is found. I think this would be the safest approach and saving the user time by following the fail fast philosophy.

2025-08-27 01:05 UTC, PhilippSchmelter commented on src/main/java/edu/ie3/datamodel/io/source/influxdb/InfluxDbWeatherSource.java
> +          if (!timeBasedValues.isEmpty()) {
I tested throwing an exception when timeBasedValues is empty, but that broke existing behavior and tests. For now we keep it simple: invalid coordinates throw a NoDataException, but valid coordinates with no data just return an empty series. Or do we really want it that strict? If so we could use my last commit which I reverted again.

2025-08-29 14:19 UTC, sebastian-peter requested changes
While looking through this, it came to my mind that some of these errors we could try and heal instead, before throwing an exception. 

I realize this requires a bit more effort, but maybe it still makes sense to handle it in this PR? On the other hand, SIMONA has to deal with these new types of exceptions anyway, and at a later step it would crash less because we healed the problem instead.

2025-08-29 14:19 UTC, sebastian-peter commented on CHANGELOG.md
> +- Added explicit handling for cases where no weather data is received from any source [#554](https://github.com/ie3-institute/PowerSystemDataModel/issues/554)
Reminder to move this to the `Unreleased/Snapshot` section

2025-08-29 14:19 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/source/couchbase/CouchbaseWeatherSource.java
> +      throw new NoDataException("No coordinate ID found for the given point: " + coordinate);
Logging an error is obsolete when we also throw and exception in the next line, imho

2025-08-29 14:19 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/source/couchbase/CouchbaseWeatherSource.java
> +    }
Hmm. I think there's a way to heal this instead of breaking right away.
I'd say, if for a coordinate we cannot retrieve weather data, we try to provide the last available data (the available data for the last point in time _before_ now) first. In this case, we also log a warning. 
If that also fails though, we should throw an exception.

2025-08-29 14:19 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/source/csv/CsvWeatherSource.java
> +    }
Same as above

2025-08-29 14:19 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/source/couchbase/CouchbaseWeatherSource.java
> +                      "No valid weather data found for the given date and coordinate."));
Same here: Maybe try to take an earlier data point instead?

2025-08-29 14:19 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/source/csv/CsvWeatherSource.java
> +                    "No weather data found for the given coordinate: " + coordinate));
Same as above

2025-08-29 14:19 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/source/influxdb/InfluxDbWeatherSource.java
> +          if (!timeBasedValues.isEmpty()) {
It'd be great to have equivalent behavior across types of data sources, at least where it's possible

2026-03-17 10:01 UTC, danielfeismann requested changes
Thanks for including the steps for possible healing of missing data. I have some additions and questions.

2026-03-17 10:01 UTC, danielfeismann commented on CHANGELOG.md
> +- Added explicit handling for cases where no weather data is received from any source [#554](https://github.com/ie3-institute/PowerSystemDataModel/issues/554)
Please move this to the end of this list.

2026-03-17 10:01 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/io/source/couchbase/CouchbaseWeatherSource.java
>    private static final String DEFAULT_TIMESTAMP_PATTERN = "yyyy-MM-dd'T'HH:mm:ssxxx";
the timestamp pattern is also unused

2026-03-17 10:01 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/io/source/WeatherSource.java
> +    }
If we encounter data inconsistencies, would it make sense to throw an exception here? It might not be the best place to do so, but if the times are mixed up like this, other things won't work as expected either.

2026-03-17 10:01 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/io/source/WeatherSource.java
> +  protected static boolean isFallbackAcceptable(
I would prefer to have some test on this method as well.

2026-03-17 10:01 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/io/source/WeatherSource.java
> +      // Two consecutive known timestamps are identical — step size cannot be determined
I'm wondering if, in this case, we should use requested and fallback/stepReference to determine step size. What do you thing? Maybe I'm wrong.

2026-03-17 10:01 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/io/source/WeatherSource.java
> +      // Two consecutive known timestamps are identical — step size cannot be determined
Ah, in that case step == gap and so we are always within the limits, right?

2026-03-17 10:01 UTC, danielfeismann commented on src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvWeatherSourceIconTest.groovy
> +    def farFutureTime = IconWeatherTestData.TIME_17H.plusHours(10)
Just minor, however I guess it would be good to test closer to the edge of the max step size. E.g., 4 would also work, right? Same at the other tests.

2026-03-17 10:01 UTC, danielfeismann commented on src/test/groovy/edu/ie3/datamodel/io/source/influxdb/InfluxDbWeatherSourceCosmoIT.groovy
>      def timeseries_193186 = new IndividualTimeSeries(null,
this is no longer used.

2026-03-17 10:01 UTC, danielfeismann commented on src/test/groovy/edu/ie3/datamodel/io/source/sql/SqlWeatherSourceIconIT.groovy
> +
Please add the case for returning partial results here as well. Or is there a reason that this is already covered?

2026-03-17 10:01 UTC, danielfeismann commented on src/main/java/edu/ie3/datamodel/io/source/influxdb/InfluxDbWeatherSource.java
> +      if (!fallbackValues.isEmpty()) {
there are some duplications. May it is possible to reduce them? However, please check carefully if this makes sense or complicates this more than it helps...

2026-03-22 15:22 UTC, PhilippSchmelter commented on src/main/java/edu/ie3/datamodel/io/source/WeatherSource.java
> +    }
you are right. throwing here is cleaner.

2026-03-22 15:52 UTC, PhilippSchmelter commented on src/main/java/edu/ie3/datamodel/io/source/WeatherSource.java
> +      // Two consecutive known timestamps are identical — step size cannot be determined
you are right! same result either way

2026-03-22 15:56 UTC, PhilippSchmelter commented on src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvWeatherSourceIconTest.groovy
> +    def farFutureTime = IconWeatherTestData.TIME_17H.plusHours(10)
also true. i changed to 3 and 4

2026-03-22 15:59 UTC, PhilippSchmelter commented on src/test/groovy/edu/ie3/datamodel/io/source/influxdb/InfluxDbWeatherSourceCosmoIT.groovy
>      def timeseries_193186 = new IndividualTimeSeries(null,
removed

2026-03-22 16:11 UTC, PhilippSchmelter commented on src/test/groovy/edu/ie3/datamodel/io/source/sql/SqlWeatherSourceIconIT.groovy
> +
Good Point!. Ive overlooked that. Added it to both Influx Tests too

2026-03-22 16:17 UTC, PhilippSchmelter commented on src/main/java/edu/ie3/datamodel/io/source/influxdb/InfluxDbWeatherSource.java
> +      if (!fallbackValues.isEmpty()) {
i extracted it into a little helper method just for InfluxDb. Implementing that helper across all Sources wouldnt be clean in my opinion. Adding that Method to the BaseClass, would just thicken and couple the classes unnecessary

2026-03-23 07:36 UTC, danielfeismann reviewed
Thanks for considering the discussed points. This looks good to me! However, since weather is very important within our simulations I would prefer to have also a look by @staudtMarius on this.

2026-03-23 09:55 UTC, staudtMarius requested changes
Here are some first remarks from my side.

2026-03-23 09:55 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/io/source/csv/CsvWeatherSource.java
> +  @Override
Why did you change the order of the methods?

2026-03-23 09:55 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/io/source/couchbase/CouchbaseWeatherSource.java
> +      log.warn(
You are not excluding these coordinates from checking.

2026-03-23 09:55 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/io/source/influxdb/InfluxDbWeatherSource.java
> +      log.warn(
You are not skipping these coordinates with you current implementation.

2026-03-23 09:55 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/io/source/sql/SqlWeatherSource.java
> +      log.warn(
Same as in the other database sources.

2026-03-23 09:55 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/io/source/sql/SqlWeatherSource.java
> +    if (!timeBasedValues.isEmpty()) {
This is the same as in the other sources. Can you abstract these lines and put them into the abstract class `WeatherSource`?

2026-03-23 12:41 UTC, PhilippSchmelter commented on src/main/java/edu/ie3/datamodel/io/source/csv/CsvWeatherSource.java
> +  @Override
could you please specify that question? I checked the diff against dev and only changes i found are that the methods we used to have are a bit longer here and there. Also we got a new getTimeKeysAfter Method, but no real change in order. Please correct me if im wrong

2026-03-23 12:49 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/io/source/csv/CsvWeatherSource.java
> +  @Override
Ok. I mistook this for another method based on the input parameters.

2026-04-10 15:17 UTC, staudtMarius requested changes
Some remarks from my side.

2026-04-10 15:17 UTC, staudtMarius commented on CHANGELOG.md
> +- Added explicit handling for cases where no weather data is received from any source [#554](https://github.com/ie3-institute/PowerSystemDataModel/issues/554)
Could you move this to the end?

2026-04-10 15:17 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/exceptions/NoDataException.java
> + * Exception that should be used whenever no data is received{@link
I think you are missing a word here.

2026-04-10 15:17 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/io/source/couchbase/CouchbaseWeatherSource.java
> +  private TimeBasedValue<WeatherValue> getLastKnownWeather(
SInce the checking of the fallback values is simmilar for all the weather source implementation, I think we schould abstract them and move this abtract method to the base class.
But this could also be done in another issue.

2026-04-22 10:30 UTC, PhilippSchmelter commented on src/main/java/edu/ie3/datamodel/io/source/couchbase/CouchbaseWeatherSource.java
> +  private TimeBasedValue<WeatherValue> getLastKnownWeather(
good point! this saves us a lot of lines :D

2026-05-21 08:21 UTC, staudtMarius reviewed
I have two small remarks.

2026-05-21 08:21 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/io/source/csv/CsvWeatherSource.java
> +        .ifPresent(fallbacks::add);
I think that we will add more than just two elements here. Have you checked, if this could lead to a problem?

2026-05-21 08:21 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/io/source/sql/SqlWeatherSource.java
> +    if (!timeBasedValues.isEmpty()) {
The first if statement can be removed.

2026-05-21 16:27 UTC, PhilippSchmelter commented on src/main/java/edu/ie3/datamodel/io/source/sql/SqlWeatherSource.java
> +    if (!timeBasedValues.isEmpty()) {
The if (!timeBasedValues.isEmpty()) is needed. Right below it is return timeBasedValues.get(0), which would throw IOOB on an empty list. Also, the fallback query and applyFallbackOrThrow only run because of this if. Without it the early return always fires and the fallback path is dead code.

Please correct me if i am wrong here! :)

2026-05-21 16:32 UTC, PhilippSchmelter commented on src/main/java/edu/ie3/datamodel/io/source/csv/CsvWeatherSource.java
> +        .ifPresent(fallbacks::add);
Actually it was capped at 2, but fair point it wasn't really clear. Refactored it to a for loop with i < 2 so the cap is obvious now.

2026-05-22 05:17 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/io/source/sql/SqlWeatherSource.java
> +    if (!timeBasedValues.isEmpty()) {
I checked it again. Your right, we need the if statement.

2026-05-22 05:18 UTC, staudtMarius approved these changes

2026-05-22 05:32 UTC, merged