Add information about time series content to file name
ie3-institute/PowerSystemDataModel pull request #215
Opened 2020-10-08 14:55 UTC by ckittl

Closes #214, address #208 before, pls.

2020-10-08 19:02 UTC, johanneshiry commented
Would prefer merging #208 before to have less struggle with the javadocs which makes a careful review nearly impossible.

2020-10-13 09:05 UTC, ckittl commented
> Would prefer merging #208 before to have less struggle with the javadocs which makes a careful review nearly impossible.

Did so, you are good to go. ;-)

2020-10-13 09:08 UTC, ckittl commented
!test

2020-10-14 11:41 UTC, johanneshiry requested changes
Generally LGTM - pls address codacy issues + the minor changes I commented

2020-10-14 11:41 UTC, johanneshiry commented on docs/readthedocs/io/csvfiles.rst
> +| c       | | An energy price (e.g. in €/MWh; c stands for charge".                                                        |
```suggestion
| c       | | An energy price (e.g. in €/MWh; c stands for charge).                                                        |
```

2020-10-14 11:41 UTC, johanneshiry commented on src/main/java/edu/ie3/datamodel/io/factory/EntityData.java
> +  protected final Map<String, String> fieldsToAttributes;
![Nope](https://media1.tenor.com/images/583ac7bd474a80ee73b3f891049f7aa7/tenor.gif?itemid=12298561)
```suggestion
  pivate final Map<String, String> fieldsToAttributes;
```

use `getFieldsToValues()` instead

2020-10-14 11:41 UTC, johanneshiry commented on src/main/java/edu/ie3/datamodel/io/factory/EntityData.java
> +  protected final Class<? extends UniqueEntity> entityClass;
```suggestion
 private  final Class<? extends UniqueEntity> entityClass;
```

2020-10-14 13:06 UTC, merged