Reading in time series
ie3-institute/PowerSystemDataModel pull request #220
Opened 2020-10-14 14:12 UTC by ckittl

Closes #219

2020-10-21 14:06 UTC, johanneshiry requested changes
Thank you very much for your work. I added some comments and change requests that I would prefer to be addressed before merging. In general I'm really looking forward having the time series I/O capabilities available on the PSDM soon! :)

2020-10-21 14:06 UTC, johanneshiry commented on src/main/java/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesSource.java
> +  public TimeSeriesContainer getTimeSeries() {
Pls add this to the `TimeSeriesSource` interface

2020-10-21 14:06 UTC, johanneshiry commented on src/main/java/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesSource.java
> +  private <V extends Value> Set<IndividualTimeSeries<V>> readIn(
```suggestion
  private <V extends Value> Set<IndividualTimeSeries<V>> read(
```

2020-10-21 14:06 UTC, johanneshiry commented on src/main/java/edu/ie3/datamodel/models/timeseries/TimeSeriesContainer.java
> +        Objects.requireNonNull(
👍  for this approach!

2020-10-21 14:06 UTC, johanneshiry commented on src/main/java/edu/ie3/datamodel/io/source/csv/CsvRawGridSource.java
> +  private <T extends AssetTypeInput, C extends ConnectorInput>
```suggestion
  private <T extends AssetTypeInput>
```

2020-10-23 14:01 UTC, ckittl commented on src/main/java/edu/ie3/datamodel/io/factory/EntityFactory.java
>      TimeTools.initialize(ZoneId.of("UTC"), Locale.GERMANY, "yyyy-MM-dd HH:mm:ss");
Intend to do this in a separate PR.

2020-10-23 14:05 UTC, ckittl commented on src/main/java/edu/ie3/datamodel/io/factory/result/ThermalResultFactory.java
>      ZonedDateTime zdtTimestamp = TimeTools.toZonedDateTime(data.getField(TIMESTAMP));
Intend to do this in a separate PR.

2020-10-23 14:05 UTC, ckittl commented on src/main/java/edu/ie3/datamodel/io/factory/timeseries/TimeBasedSimpleValueFactory.java
> +  protected TimeBasedValue<V> buildModel(SimpleTimeBasedValueData<V> data) {
At least we come to the same conclusion. 😂

2020-10-23 14:23 UTC, ckittl commented
Removal of deprecated `TimeTools` will be addressed with #225.

2020-10-26 18:11 UTC, johanneshiry commented
!test

2020-10-26 19:35 UTC, johanneshiry approved these changes

2020-10-26 19:35 UTC, merged