Change Irradiation's unit
ie3-institute/PowerSystemDataModel pull request #253
Opened 2020-11-25 13:19 UTC by mia-krause

solves #250

2020-12-08 07:35 UTC, johanneshiry submitted a review, later dismissed
LGTM - however before merging it would prefer als having @ckittl taking a look at it to ensure that everything considering the time based value factories works as expected.

If you're fine with this @ckittl feel free to merge and delete the branch

2020-12-08 07:57 UTC, ckittl requested changes

2020-12-08 07:57 UTC, ckittl commented on src/main/java/edu/ie3/datamodel/models/StandardUnits.java
> +  public static final Unit<EnergyDensity> ENERGY_DENSITY = KILOWATTHOUR_PER_SQUAREMETRE;
```suggestion
   * Energy per Area, used as an outdated dimension for {@link StandardUnits#IRRADIATION} in
   * kWh/m²
   *
   * @deprecated Use {@link Irradiation} together with {@link StandardUnits#IRRADIATION}
   */
   @Deprecated
  public static final Unit<EnergyDensity> ENERGY_DENSITY = KILOWATTHOUR_PER_SQUAREMETRE;
```

2020-12-08 10:57 UTC, mia-krause commented
The checks fail because of the new deprecated tag, but I would leave the issue open in sonarqube, so we remember to remove it in the future.

2020-12-09 12:43 UTC, ckittl approved these changes

2020-12-09 12:43 UTC, merged