Restructuring SQL sources and introducing TimeSeriesTypeSource
ie3-institute/PowerSystemDataModel pull request #546
Opened 2022-02-24 16:15 UTC by sebastian-peter

Resolves #515 and #545

2022-02-24 18:04 UTC, sebastian-peter commented
Coverage quality gate fails in large parts because of deprecations. So, pls go ahead with reviews if you like

2022-03-10 14:38 UTC, t-ober requested changes
Thanks a lot for tackling this!

2022-03-10 14:38 UTC, t-ober commented on src/main/java/edu/ie3/datamodel/io/source/sql/SqlTimeSeriesMappingSource.java
> +public class SqlTimeSeriesMappingSource
The `TimeSeriesMappingSource` don't do much anymore. It might make sense to include the functionality to get the mapping in the respective sources.

2022-03-10 16:21 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/connectors/CsvFileConnector.java
> +      if (!(o instanceof CsvIndividualTimeSeriesMetaInformation that)) return false;
Check line 490 of the old code below

2022-03-10 16:24 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesTypeSourceIT.groovy
> +		def actual = source.timeSeriesMetaInformation
It's a [feature of groovy](https://groovy-lang.org/style-guide.html#_getters_and_setters)

2022-03-15 17:34 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/source/TimeSeriesUtils.java
> +}
Great catch, moved it to the existing class. To your second point, we already had a discussion about this (if you remember). Scapegoat doesn't like traits having constants, that's why I moved it to a separate class.

2022-03-15 17:43 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/source/sql/SqlTimeSeriesSource.java
> +  @Deprecated(since = "3.0", forRemoval = true)
True that

2022-03-15 17:46 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/source/sql/SqlTimeSeriesSource.java
> +        + "time_series = '"
Does make sense for now, at least until we might introduce fixed column names

2022-03-15 17:47 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/source/sql/SqlTimeSeriesTypeSource.java
> +                        entry.getTimeSeries(), entry.getColumnScheme())));
As per discussions, this is not too trivial too fix, so I created a new issue: #565

2022-03-16 11:13 UTC, t-ober commented on src/main/java/edu/ie3/datamodel/io/source/TimeSeriesUtils.java
> +}
you're right

2022-03-16 11:25 UTC, t-ober approved these changes
LGTM 

But we have a little too much duplicated code for sonarqube's taste

2022-03-16 13:43 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/source/TimeSeriesTypeSource.java
> +    public boolean equals(Object o) {
@sonatype-lift ignore

2022-03-16 13:44 UTC, merged