Add temperature dependant load profile
ie3-institute/PowerSystemDataModel pull request #606
Opened 2022-05-31 13:31 UTC by t-ober

2022-05-31 14:41 UTC, sebastian-peter approved these changes
LGTM

2022-05-31 14:41 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/models/TemperatureDependantLoadProfile.java
> +public enum TemperatureDependantLoadProfile implements StandardLoadProfile {
Compared to `BdewLoadProfile`, the parsing method `get(String key)` and `toString()` are missing. If you think that you won't need them this is totally find, just a heads up here.

2022-05-31 14:49 UTC, sebastian-peter requested changes

2022-05-31 14:49 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/models/StandardLoadProfile.java
> +    return Stream.concat(
The exception String in line 43 is not correct anymore

2022-06-02 08:51 UTC, danielfeismann approved these changes
LGTM, thanks :)

2022-06-03 11:32 UTC, sebastian-peter requested changes
Looks great overall, thanks. I just found some (mostly minor) points that might be worth addressing.

2022-06-03 11:32 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/models/profile/LoadProfile.java
> +    String filterKey = key.toLowerCase().replaceAll("[-_]*", "");
This should probably also be used in `getProfile` below for consistency. Maybe find a common method?

2022-06-03 11:32 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/io/naming/FileNamingStrategyTest.groovy
> +		LoadProfileInput | UUID.fromString("bee0a8b6-4788-4f18-bf72-be52035f7304") | BdewStandardLoadProfile.G3 || "test_grid" + File.separator + "input" + File.separator + "global" + File.separator + "lpt
Indentation

2022-06-03 11:32 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/models/LoadProfileTest.groovy
> +		key     || expected
Indentation

2022-06-03 11:32 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/models/LoadProfileTest.groovy
> +	def "Load profiles are parsed correctly from correct input" () {
I also would've loved to see a test for throwing the exception when providing an unknown key, but this was not implemented before, so I wouldn't expect you to implement it.  Just if you feel like it...

2022-06-03 11:32 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/utils/validation/SystemParticipantValidationUtilsTest.groovy
> +		SystemParticipantTestData.loadInput.copy().loadprofile(null).build() || new InvalidEntityException("No standard load profile defined for load", invalidLoad)
Indentation

2022-06-03 11:44 UTC, t-ober commented on CHANGELOG.md
> +- `TemperatureDependantLoadProfile`s for depiction of profile behavior of night storage heating and heat pumps [#601](https://github.com/ie3-institute/PowerSystemDataModel/issues/601)
see line 52 that was my attempt at addressing that

2022-06-03 13:03 UTC, sebastian-peter approved these changes
Thanks!

2022-06-03 13:30 UTC, merged