Introduce thermal containers
ie3-institute/PowerSystemDataModel pull request #619
Opened 2022-06-16 11:46 UTC by ckittl

Resolves #134

2022-06-20 18:29 UTC, ckittl commented
Sorry for not passing the quality gate. But I won't write tests for records. ;-)

2022-06-28 14:41 UTC, sebastian-peter requested changes
I agree testing e.g. the getters of a record does not make sense, but testing `allEntitiesAsList()` might? Thanks anyway for the work.

2022-06-28 14:41 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/models/input/container/ThermalGrid.java
> +    ThermalBusInput bus, Set<ThermalHouseInput> houses, Set<ThermalStorageInput> storages)
Do you think it'd pay off to split thermal storages into their subtypes CylindricalStorage, ...?

2022-06-28 14:41 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/models/input/container/ThermalUnits.java
> +   */
Doesn't this ScalaDoc fit the class better, at the top?

2022-06-28 14:41 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/models/input/thermal/ThermalUnitInput.java
> +   * @param thermalBus thermal bus, a thermal unit is connected to
hank you very much :)

2022-06-28 15:00 UTC, ckittl commented on src/main/java/edu/ie3/datamodel/models/input/thermal/ThermalUnitInput.java
> +   * @param thermalBus thermal bus, a thermal unit is connected to
... or traveling with deutsche bahn!

2022-07-10 14:42 UTC, sebastian-peter approved these changes
Ok I just provided some really quick tests for `allEntitiesAsList()` and now the test coverage is good :)
Thanks for the contribution!

2022-07-10 14:43 UTC, merged