Find and add standard asset types
ie3-institute/PowerSystemDataModel pull request #687
Opened 2022-10-17 08:07 UTC by staudtMarius

Resolves #642

2023-01-20 14:00 UTC, sebastian-peter submitted a review, later dismissed
A proper review has to happen still, this is just a hint to add a meaningful message about what was added to the _changelog_  :)

2023-07-03 07:47 UTC, danielfeismann requested changes
This looks good to me, thanks for your work. Just a minor change I would suggest to change in the changelog.

2023-07-03 07:47 UTC, danielfeismann commented on CHANGELOG.md
> +- Some standard asset types [#642](https://github.com/ie3-institute/PowerSystemDataModel/issues/642)
```suggestion
- Added some standard asset types to documenation [#642](https://github.com/ie3-institute/PowerSystemDataModel/issues/642)
```

2023-07-05 07:19 UTC, danielfeismann approved these changes
Thanks for improving this!

2023-07-05 07:20 UTC, merged