Vb/#586 grid io it
ie3-institute/PowerSystemDataModel pull request #709
Opened 2022-12-09 15:24 UTC by vickybung1

Resolves #586

2022-12-21 14:33 UTC, vickybung1 commented
#710 must be solved first

2023-01-10 12:57 UTC, vickybung1 commented
Additionally resolves #502

2023-01-24 16:06 UTC, sebastian-peter commented
!test

2023-01-25 16:48 UTC, sebastian-peter requested changes
Some minor remarks from my side

2023-01-25 16:48 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/io/GridIoIT.groovy
> +    def folderpath = new String(jointGridFolderPath)
You could use the String `jointGridFolderPath` directly below

2023-01-25 16:48 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/io/GridIoIT.groovy
> +    }
This you could put into a `cleanupSpec()`, similar to how it works in `CsvFileConnectorTest`

2023-01-25 16:48 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/io/GridIoIT.groovy
> +    firstGridContainer.equals(secondGridContainer)
Could be replaced by `firstGridContainer == secondGridContainer` (this works in Groovy)

2023-01-25 16:58 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/io/GridIoIT.groovy
> +    }
Also I just realized this doesn't work and the files are not deleted from my temp folder. Maybe you could look into this

2023-02-13 13:17 UTC, sebastian-peter commented
Note to myself: we should use the updated csv sources from https://github.com/ie3-institute/simona/pull/424 once they are final.

2023-02-13 13:18 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/io/GridIoIT.groovy
> +    }
I just swapped two lines of code and it works for me now... Please check for yourself also.

2023-02-16 09:05 UTC, sebastian-peter approved these changes
Ok I only made some minor final adaptions. Let's get this merged!

2023-02-16 09:05 UTC, merged