Refactor data source to throw exception instead of returning optionals
ie3-institute/PowerSystemDataModel pull request #712
Opened 2022-12-15 13:27 UTC by staudtMarius

Resolves #707

2023-04-03 08:21 UTC, danielfeismann requested changes
Thanks for your work done here! This looks all fine for me, just a minor question.

2023-04-25 15:28 UTC, danielfeismann reviewed
LGTM and could merged in my point of view. @sebastian-peter mentioned that he also wanted to have a look here

2023-05-16 14:33 UTC, staudtMarius commented
!test

2023-06-30 13:00 UTC, sebastian-peter requested changes
Looks good overall, your coding is improving! 

Could you take care of these points, before I re-review? 
In general, please also have an eye on SonarQube code smells.

2023-07-04 10:34 UTC, staudtMarius commented
!test

2023-07-07 11:36 UTC, staudtMarius commented
test

2023-07-07 11:37 UTC, staudtMarius commented
!test

2023-07-25 15:21 UTC, sebastian-peter requested changes
Some more comments from my side :)

2023-07-25 15:38 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/io/source/ThermalSource.java
> +  public Try<Set<ThermalHouseInput>, FailureException> buildThermalHouseInputEntities(
Thanks. I missed that part.

2023-07-26 10:10 UTC, danielfeismann approved these changes

2023-07-26 10:10 UTC, merged