Use nio paths instead of strings
ie3-institute/PowerSystemDataModel pull request #742
Opened 2023-02-07 10:51 UTC by staudtMarius

Resolves #723

2023-04-03 13:26 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/io/connectors/CsvFileConnectorTest.groovy
> +    def baseDirectory = tmpDirectory
Maybe rename the field `tmpDirectory` to `baseDirectory`, so that this variable can be removed (same below)?

2023-04-03 13:36 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/io/csv/CsvFileDefinitionTest.groovy
> +    directory = Path.of("test").resolve("grid")
Same as above, you don't need the call to `resolve` here

2023-04-03 13:38 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/io/csv/CsvFileDefinitionTest.groovy
> +    Path.of("test", "grid") || Paths.get("test", "grid", this.fileName)
Could be `Paths.of(...)` for the expected part as well, you'd also need one import less then

2023-04-03 13:43 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/io/naming/FileNamingStrategyTest.groovy
> +    LoadResult               || Paths.get("test_grid", "results", "participants")
You could replace all `Paths.get` in here with `Path.of`, but it's not super important

2023-04-03 13:46 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvTestDataMeta.groovy
> +    return Paths.get(CsvTestDataMeta.getResource(directory).toURI())
Path.of(...)

2023-04-03 13:48 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesMappingSourceIT.groovy
> +    source = new CsvTimeSeriesMappingSource(";", timeSeriesFolderPath as Path, new FileNamingStrategy())
Doesn't seem like the cast is necessary here?

2023-04-03 13:48 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesMetaInformationSourceIT.groovy
> +    source = new CsvTimeSeriesMetaInformationSource(";", timeSeriesFolderPath as Path, new FileNamingStrategy())
Same as above, cast needed?

2023-04-03 13:49 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesSourceIT.groovy
> +    source = new CsvTimeSeriesSource(";", timeSeriesFolderPath as Path, new FileNamingStrategy(), UUID.fromString("76c9d846-797c-4f07-b7ec-2245f679f5c7"), Path.of("its_ph_76c9d846-797c-4f07-b7ec-2245
cast

2023-04-03 13:49 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesSourceIT.groovy
> +    new CsvTimeSeriesSource(";", timeSeriesFolderPath as Path, new FileNamingStrategy(), UUID.fromString("fbc59b5b-9307-4fb4-a406-c1f08f26fee5"), Path.of("file/not/found"), HeatAndPValue, factory)
cast

2023-04-03 13:49 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesSourceTest.groovy
> +    def source = new CsvTimeSeriesSource(";", timeSeriesFolderPath as Path, new FileNamingStrategy(), UUID.fromString("2fcb3e53-b94a-4b96-bea4-c469e499f1a1"), Path.of("its_c_2fcb3e53-b94a-4b96-bea4-c
cast

2023-04-03 13:49 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesSourceTest.groovy
> +    CsvTimeSeriesSource.getSource(";", timeSeriesFolderPath as Path, fileNamingStrategy, metaInformation)
cast

2023-04-03 13:50 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesSourceTest.groovy
> +    def actual = CsvTimeSeriesSource.getSource(";", timeSeriesFolderPath as Path, fileNamingStrategy, metaInformation)
cast

2023-06-01 17:04 UTC, sebastian-peter requested changes
Found some things that could be adapted a bit further. All in all it looks quite already though.
We'll be waiting for #773 before merging this anyway though.

2023-06-05 10:59 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/io/csv/CsvFileDefinition.java
> +                : "");
I moved this check to the new ``FileDefinition`` class.

2023-06-05 12:11 UTC, staudtMarius commented on src/main/java/edu/ie3/datamodel/io/naming/FileNamingStrategy.java
> +      return maybeDirectoryName;
I readded this part of the code.

2023-06-07 11:43 UTC, staudtMarius commented
!test

2023-06-09 14:18 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/csv/FileDefinition.java
Ok hmm, what's the advantage of this over just using a `Path file`? Why have three fields, of which one is just the combination of the other two, if `fullPath` conveys all information we need?

2023-06-21 08:16 UTC, sebastian-peter requested changes
Some last questions

2023-06-21 08:16 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvRawGridSourceTest.groovy
> +    source = new RawGridSource(typeSource, new CsvDataSource(csvSep, gridDefaultFolderPath as Path, fileNamingStrategy))
Just curious, why is this necessary? The fields should already be of the right type

2023-06-21 08:16 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/datamodel/io/naming/FileNamingStrategyTest.groovy
> -    idFilePath.get() ==  defaultHierarchy.baseDirectory.get() + File.separator + "prefix_coordinates_suffix"
Where did this go?

2023-06-21 12:08 UTC, sebastian-peter approved these changes
Ok we got it! Thanks @staudtMarius!

2023-06-21 12:09 UTC, merged