Refactor and harmonize CSV and SQL data sources
ie3-institute/PowerSystemDataModel pull request #773
Opened 2023-03-08 08:42 UTC by jo-bao

- refactor CSV and SQL data sources to use the methods for creating entities
- implement IdCoordinateSource for SQL

2023-03-08 13:33 UTC, jo-bao commented
!test

2023-03-08 13:38 UTC, jo-bao commented
!test

2023-03-10 07:52 UTC, jo-bao commented
!test

2023-03-10 08:38 UTC, t-ober commented
@sonatype-lift test

2023-03-10 08:40 UTC, t-ober commented
@sonatype-lift help

2023-03-28 18:10 UTC, sebastian-peter requested changes
Nice work, looks well thought-out for the most part. I got some points below, I think they're more than enough for now :D
Please hit me up with any questions

2023-03-28 18:10 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/source/IdCoordinateSource.java
> +public class IdCoordinateSource implements DataSource {
For weather coordinates, we have some relevant changes in #694, something we should keep in mind here. I think the changes can be combined though.

2023-03-28 18:14 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/source/sql/SqlTimeSeriesSource.java
>    private final UUID timeSeriesUuid;
Seems to not apply anymore

2023-04-05 07:09 UTC, jo-bao commented on src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvSystemParticipantSourceTest.groovy
That's the plan, but I haven't tested it yet.

2023-05-31 13:07 UTC, sebastian-peter requested changes
Ok these are my comments for now, haven't checked the tests yet because I think it makes more sense once this is final.

Two more things to check out besides those comments:
- SonarQube reports 20 new code smells, could you take care of these? Some might even be connected 
- Readthedocs documentation might need some updates, found at least `csvfiles.md` which has outdated info

2023-05-31 14:10 UTC, jo-bao commented on src/main/java/edu/ie3/datamodel/io/source/sql/SqlDataSource.java
> +  protected Stream<Map<String, String>> buildStreamByEntityClass(
I think we'll need it when we implement the SQL sources for system participants and grid elements.

2023-05-31 14:14 UTC, jo-bao commented on src/main/java/edu/ie3/datamodel/io/source/WeatherSource.java
Oh yes, I'll shift it to CsvWeatherSource.

2023-06-09 12:37 UTC, sebastian-peter requested changes
Almost there, I think, besides some some pedantic points from my side.
Please also take a look at SonarQube, some new issues popped up :)

2023-06-09 12:37 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/source/csv/CsvIdCoordinateSource.java
> +  public Stream<Map<String, String>> buildStreamWithFieldsToAttributesMap() {
Why?

2023-06-09 12:37 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesSource.java
> +      Function<Map<String, String>, Optional<TimeBasedValue<V>>> fieldToValueFunction,
Isn't `fieldToValueFunction` always the function `createTimeBasedValue`?

2023-06-12 08:29 UTC, jo-bao commented on src/main/java/edu/ie3/datamodel/io/source/WeatherSource.java
> +  }
I think you mean CsvWeatherSource :D

2023-06-13 15:24 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/source/csv/CsvTimeSeriesSource.java
> +      Function<Map<String, String>, Optional<TimeBasedValue<V>>> fieldToValueFunction,
Ok what you did there was also helpful, it's not what I meant though :D Not that important though

2023-06-13 15:25 UTC, sebastian-peter approved these changes
Thanks for putting all this work in here! I think you've found some really nice abstractions that should make the codebase a lot more usable.

2023-06-14 07:08 UTC, merged