Adding enhanced error handling for invalid column names in coordinate sources
ie3-institute/PowerSystemDataModel pull request #807
Opened 2023-05-11 12:44 UTC by staudtMarius

Resolves #670

2023-06-22 08:31 UTC, sebastian-peter requested changes
Please also check out the SonarQube warnings. To solve them, it could be helpful to check out how `org.slf4j.Logger` can format log messages with supplied objects

2023-06-22 08:31 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/source/csv/CsvIdCoordinateSource.java
> +
I believe it'd be a lot more efficient to check the column headers only once (after line 154) and not repeatedly for every row read.

2023-06-22 08:31 UTC, sebastian-peter commented on src/main/java/edu/ie3/datamodel/io/factory/timeseries/IdCoordinateFactory.java
> +      throw new InvalidColumnNameException(
Thanks for re-using the existing exception type!

2023-07-26 11:35 UTC, sebastian-peter commented
Ok I just realized we already have a validation in `Factory#validateParameters`, which is called by `Factory#get(D)`, which is called everytime that any entity is parsed from some source. The problem with IdCoordinateSources is that these validations are called _after_ some other things, like duplicate removal, happened, that already access the data and fail if some column is missing.

Looking at `Factory.get()` as a whole, I'd describe two main issues:
1. validation is sometimes, like in the case of `IdCoordinateSource`, called too late
2. validation is executed for _every single_ data point parsed from `Factory.get()`, which is pretty costly

So I think there's a way to fix both at the same time: Validate column names once during initialization (and early enough).

With regards to this PR: We could merge it to fix the problem in `IdCoordinateSource`, but we then have to remember removing this again once validation is fixed in general.

@staudtMarius @t-ober @danielfeismann

2023-11-10 10:45 UTC, staudtMarius commented
Will be resolved in #926.

2023-11-10 10:45 UTC, closed without merging