adapting dod in documentation
ie3-institute/PowerSystemDataModel pull request #942
Opened 2023-11-27 09:54 UTC by SimonHuette

resolves #872

2023-12-01 12:06 UTC, sebastian-peter submitted a review, later dismissed
Please also add a line to the changelog here :)

2024-02-14 09:48 UTC, sebastian-peter commented
Postponed until we deal with storages in simona

2024-06-10 10:43 UTC, jo-bao requested changes
Just a few small points

2024-06-10 10:43 UTC, jo-bao commented on docs/readthedocs/models/input/participant/storage.md
>     * - em
em should be moved to "entity model"

2024-06-10 11:26 UTC, danielfeismann commented on docs/readthedocs/models/input/participant/storage.md
>     * - em
Good catch!

2024-06-10 12:23 UTC, jo-bao approved these changes
Now for me it's fine!

2024-06-11 06:47 UTC, merged